"""Refresh pinned OFL font assets; no network is used by product consumers."""
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
import hashlib, io, json, re, tarfile, urllib.request

ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / 'resources/fonts'
PACKAGES = ['noto-sans', 'noto-sans-jp', 'noto-sans-sc', 'noto-sans-tc',
            'noto-sans-devanagari', 'noto-sans-bengali', 'noto-sans-arabic',
            'noto-sans-hebrew', 'roboto']
SPECS = [(f'@fontsource-variable/{name}', '5.3.0', 'package/index.css', 'package/LICENSE') for name in PACKAGES]
SPECS += [('@fontsource/titillium-web', '5.3.0', 'package/400.css', 'package/LICENSE'),
          ('pretendard-gov', '1.3.9', 'package/dist/web/variable/pretendardvariable-gov-dynamic-subset.css', 'package/dist/LICENSE.txt')]

def download(spec):
    name, version, css_path, license_path = spec
    metadata = json.load(urllib.request.urlopen(f'https://registry.npmjs.org/{name}/{version}'))
    data = urllib.request.urlopen(metadata['dist']['tarball']).read()
    assert hashlib.sha1(data).hexdigest() == metadata['dist']['shasum']
    archive = tarfile.open(fileobj=io.BytesIO(data), mode='r:gz')
    family = name.split('/')[-1]
    folder = FONTS / family
    folder.mkdir(parents=True, exist_ok=True)
    css_paths = [css_path] if family != 'titillium-web' else [f'package/{w}.css' for w in [400, 600, 700]]
    css = '\n'.join(archive.extractfile(p).read().decode() for p in css_paths)
    css = css.replace(' Variable', '')
    def copy(match):
        relative = match.group(1).strip('"\'')
        member = str(Path(css_path).parent / relative)
        filename = Path(relative).name
        (folder / filename).write_bytes(archive.extractfile(member).read())
        return f'url("./fonts/{family}/{filename}")'
    css = re.sub(r'url\(([^)]+)\)', copy, css)
    (folder / 'LICENSE').write_bytes(archive.extractfile(license_path).read())
    return css, {'package': name, 'version': version, 'tarball': metadata['dist']['tarball'], 'sha256': hashlib.sha256(data).hexdigest()}

with ThreadPoolExecutor(max_workers=6) as pool:
    results = list(pool.map(download, SPECS))
css = '\n'.join(r[0] for r in results)
(ROOT / 'resources/font-faces.css').write_text(css)
(ROOT / 'src/mithril/design_system/font_faces.cljc').write_text(
    ';; Generated by scripts/vendor-locale-fonts.py; retain OFL notices in resources/fonts.\n'
    '(ns mithril.design-system.font-faces)\n(def css ' + json.dumps(css, ensure_ascii=False) + ')\n')
(ROOT / 'resources/fonts/manifest.json').write_text(json.dumps([r[1] for r in results], indent=2) + '\n')
print('Vendored', len(results), 'families,', len(list(FONTS.rglob('*.woff2'))), 'subsets')
# Brazil publishes Rawline directly; its embedded name table declares OFL 1.1.
import zipfile
url = 'https://www.gov.br/sri/pt-br/central-de-conteudo/manuais/enpp-manual/00-fonte-rawline.zip'
data = urllib.request.urlopen(url).read()
archive = zipfile.ZipFile(io.BytesIO(data))
folder = FONTS / 'rawline'
folder.mkdir(exist_ok=True)
license_text = urllib.request.urlopen('https://raw.githubusercontent.com/google/fonts/main/ofl/raleway/OFL.txt').read()
(folder / 'LICENSE').write_bytes(license_text)
for weight in [400, 500, 600, 700]:
    for suffix, style in [('', 'normal'), ('i', 'italic')]:
        filename = f'rawline-{weight}{suffix}.ttf'
        (folder / filename).write_bytes(archive.read(f'00-Fonte-Rawline/{filename}'))
        css += f'\n@font-face {{ font-family: "Rawline"; font-style: {style}; font-display: swap; font-weight: {weight}; src: url("./fonts/rawline/{filename}") format("truetype"); }}\n'
(ROOT / 'resources/font-faces.css').write_text(css)
(ROOT / 'src/mithril/design_system/font_faces.cljc').write_text(
    ';; Generated by scripts/vendor-locale-fonts.py; retain OFL notices in resources/fonts.\n'
    '(ns mithril.design-system.font-faces)\n(def css ' + json.dumps(css, ensure_ascii=False) + ')\n')
manifest = [r[1] for r in results] + [{'package': 'Rawline', 'source': url, 'sha256': hashlib.sha256(data).hexdigest()}]
(ROOT / 'resources/fonts/manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
